var items = [
"Chocolate Cookie Latte",
"Cinnamon Latte",
"Irish Latte",
"Caramello Latte",
"Chococino (Mocha)",
"Oriental Latte",
"Robert's Mocha",
"White Mocha Habenero",
"Creme Brulee Latte",
"Mocha Caramel Latte",
"Hot Raspberry Mocha",
"Penne Diavolo",
"Tuna Fish Penne",
"Beef Tagliatella",
"Spaghetti Bolognese",
"Chicken Hawaii",
"Beef Noodle",
"Chicken Noodle",
"Orange Juice",
"Lemonade",
"Coca Cola",
"Fuse Tea",
"Fruit Juice",
"Salep",
"Ayran",
"Energy Drink",
"Mineral Water",
"Turkish Dream",
"Strawberry Field",
"Vanilla Ice",
"Chocolate Dream",
"Coconut Island",
"Strawberry Magic"];

export default items